### ISSUE TITLE
Compilation questions

### ISSUE THREAD

**Issue by BabelQwerty** [enkomio/AlanFramework#10]
Hello,I wanna Figure it out how to compile src\client program to asm binrary ?

**Comment by enkomio** [comment]
Hi,

The section https://github.com/enkomio/AlanFramework?tab=readme-ov-file#compile-the-source-code provides the needed steps to compile the entire solution.

**Comment by BabelQwerty** [comment]
thx

> Hi,
> 
> The section https://github.com/enkomio/AlanFramework?tab=readme-ov-file#compile-the-source-code provides the needed steps to compile the entire solution.
