### ISSUE TITLE
It is suggested to add functions

### ISSUE THREAD

**Issue by go-bi** [enkomio/AlanFramework#3]
It will be better to add socks proxy or port forwarding function

**Comment by enkomio** [comment]
hi,
thanks for the suggestion. I'm happy to inform you that the Alan v7.0 will support SOCKS5 proxy with username/password authentication and the possibility to create a proxy chain.

The 7.0 version will be release in a couple of weeks. I'll keep this issue open until the next release.

**Comment by enkomio** [comment]
Hi,
Alan v7.0 implementing SOCKS5 Proxy release. https://github.com/enkomio/AlanFramework/releases/tag/7.0.514.10
