### ISSUE TITLE
[QUESTION] Connexion AWS server

### ISSUE THREAD

**Issue by piedacoulisse2** [enkomio/AlanFramework#4]
Hello, 

I have a question about the C2. Why is there a connexion to the web server AWS 34.252.108.5 in the app ? 

Best regards;

Piedacoulisse

**Comment by enkomio** [comment]
Hi,

the connection to that IP is necessary to obtain the public Alan server IP address. This information is handy during the creation of an agent (you have to specify a public IP address in order for the agent to connect to the server). More information on this aspect are provided in the guide (https://github.com/enkomio/AlanFramework/blob/main/doc/Alan%20Documentation%20-%20v7.0.514.10.pdf) on page 7.

**Comment by piedacoulisse2** [comment]
Ok thank for the response.

**Comment by piedacoulisse2** [comment]
You can also use to obtain the public ip  with http://api.ipify.org insteed of AWS server.

**Comment by enkomio** [comment]
yep. I might considering, for the next release, to use more than one URL to obtain the public IP, or give the possibility to disable the IP resolution at all.
