### ISSUE TITLE
Compilation Guide

### ISSUE THREAD

**Issue by piedacoulisse2** [enkomio/AlanFramework#7]
Hello, 
I wonder if you have a guide/ReadMe to compile the Server.dll file from the src folder with Visual Studio. 
Best regards,
Piedacoulisse

**Comment by enkomio** [comment]
Hi,
Unfortunately I don't have anything available yet. I plan to write a compilation guide using VS2022.

**Comment by piedacoulisse2** [comment]
Thanks.

**Comment by enkomio** [comment]
I'd like to leave this issue open until I finish to write the guide :)

**Comment by enkomio** [comment]
hi,
I modified the code and written down the steps to compile Alan. Check the README file and let me know if you encounter any problems.

**Comment by piedacoulisse2** [comment]
@enkomio Thank I will test the process as soon as possible.

**Comment by piedacoulisse2** [comment]
There is just a small mistake in the cmd prompt. 
`Release file written at: E:\Tools\Misc\out\Alan.v7.0.518.4.zip`
Insteed of : 
`Release file written at: E:\Tools\Misc\out\release\Alan.v7.0.518.4.zip`
